name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Change this based on your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Use poetry/pipenv if needed

      - name: Run Tests
        run: |
          pytest  # Change this to the test framework you use

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Production Docker image
        if: (github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradient-bot:latest -f docker/dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/gradient-bot:latest
